"""
Save and load optimized production configuration.

Profiler scripts write their results to a YAML file via update_config().
run_batch.py loads the file via load_config() to override CLI defaults.

The config only stores performance/quality knobs — physics parameters
stay in the detector YAML.

File format:
    # Generated by JAXTPC profiler
    detector_config: config/sbnd_config.yaml
    total_pad: 500000
    response_chunk: 50000
    hits_chunk: 25000
    max_keys: 4000000
    inter_thresh: 1.0
    threshold_adc: 2.0
    corr_threshold: 25.0
    max_buckets: 1000
"""

import os
from datetime import datetime

import yaml


# Fields that production_config manages — maps config key to run_batch arg name
CONFIG_FIELDS = {
    'total_pad':      'total_pad',
    'response_chunk': 'response_chunk',
    'hits_chunk':     'hits_chunk',
    'max_keys':       'max_keys',
    'inter_thresh':   'inter_thresh',
    'threshold_adc':  'threshold_adc',
    'corr_threshold': 'corr_threshold',
    'max_buckets':    'max_buckets',
}


def load_config(path):
    """Load a production config YAML. Returns dict of field -> value."""
    with open(path, 'r') as f:
        data = yaml.safe_load(f)
    if data is None:
        return {}
    return {k: v for k, v in data.items() if k in CONFIG_FIELDS or k == 'detector_config'}


def save_config(path, values, detector_config_path=None):
    """Write a full production config YAML.

    Parameters
    ----------
    path : str
        Output YAML path.
    values : dict
        Field -> value mapping. Only known CONFIG_FIELDS are written.
    detector_config_path : str, optional
        Path to the detector YAML this config was optimized for.
    """
    data = {}
    if detector_config_path:
        data['detector_config'] = detector_config_path
    data['generated'] = datetime.now().isoformat()

    for key in CONFIG_FIELDS:
        if key in values:
            data[key] = values[key]

    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, 'w') as f:
        f.write('# JAXTPC production config — generated by profiler\n')
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)


def update_config(path, updates, detector_config_path=None):
    """Update specific fields in an existing config, preserving others.

    Creates the file if it doesn't exist.

    Parameters
    ----------
    path : str
        Config YAML path.
    updates : dict
        Field -> value pairs to update.
    detector_config_path : str, optional
        Overwrite the detector_config reference.
    """
    if os.path.exists(path):
        existing = load_config(path)
    else:
        existing = {}

    existing.update({k: v for k, v in updates.items() if k in CONFIG_FIELDS})

    det_path = detector_config_path or existing.get('detector_config')
    save_config(path, existing, detector_config_path=det_path)


def apply_to_args(args, config):
    """Apply loaded config values to an argparse Namespace.

    Only overwrites args that are still at their default values.
    This lets explicit CLI args take precedence over the config file.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed CLI args from run_batch.py.
    config : dict
        From load_config().

    Returns
    -------
    argparse.Namespace
        Modified in-place and returned.
    """
    for config_key, arg_name in CONFIG_FIELDS.items():
        if config_key in config:
            setattr(args, arg_name, config[config_key])
    return args
